### ISSUE TITLE
UnstructuredGrid topology

### ISSUE THREAD

**Issue by jacobjcastaneda** [rustychris/stompy#9]
Hi Rusty, 

Sorry for the frequent questioning. 

When reading in grids, specifically UnTRIM08 and DFMGrid, is the goal to read in the *.grd file or *_net.nc file such that a cell id for a given cell is the same as it would be in the respective model output? For instance, lets say we have water depth at time n for x cells in our grid as output from dflowfm. The ndarray of interest for this slice in time would be shape(x,). Here the index in the array for a given value should correspond to the index used for a given cell. In the case of dflowfm output, I can say this value is true at the circumcenter of that cell. Therefore, its location based on the model output ... the value water_depth(n, i) is at FlowElem_xcc[i], FlowElem_ycc[i]. I was under the impression that "i" should correspond to the cell index in the UnstructuredGrid object (if using the same grid file as the model). 

I recall this being how I did things when working with UnTrim output at RMA, but right now while doing research and working with SFEI dfm output, it does not seem to hold. 

Please comment when you can.

Best,
Jacob

**Comment by rustychris** [comment]
I think I can clarify a few things, hopefully covering what you're seeing.

You may be seeing the renumbering that DFM [optionally] applies to the grid. If renumbering is enabled (or you are using a version of DFM before renumbering could be disabled), then in general the numbering of cells in your input will not match the numbering in the output. Depending on the options used during the run, you can often load the grid from the output map file rather than the input _net.nc file. Depending on DFM version and MDU settings, this may need to be loaded as a dfm grid or a ugrid grid.

Other possibly relevant points:
 1. MPI runs will generate a separate grid and map file for each rank. I do not know whether these partitioned grids are also subject to renumbering. Safest bet is to again load the grid from the map files if possible.
 2. Partitioned output from MPI runs can be combined using `dfmoutput`. Some care is required in using these files, as `dfmoutput` does not cull all of the duplicate features. I think cells are properly handled, but you may end up with duplicate edges, which can frustrate later operations on the grid. There is a `cleanup_dfm_multidomains()` method in stompy.grid.unstructured which will eliminate these duplicate features. Cell numbering should still be valid, but edge and node numbering is not preserved in this process.
 3. DFM and UnTRIM are natively 1-based, while python is natively 0-based. `UnstructuredGrid` handles remapping indices when loading such grids, but indices reported in DFM logs would still be 1-based.
 4. If running MPI, there is a very experimental class, `stompy.grid.multi_ugrid.MultiUgrid`, which can merge partitioned map files on the fly. It's fragile and new, but could be useful if `dfmoutput` is not working for you.

Hope there is something useful in there. Let me know if it's still not sorted.

-Rusty

**Comment by jacobjcastaneda** [comment]
This is immensely useful! Thank you! I used the centers defined in the _map output for my purposes, but I will look further into what you described. This was all useful, notably the issue of 1-based vs 0-based indexing between python and the modeling paradigms and the issue of the DFM settling for grid renumbering. I certainly didn't touch a setting like that, so it is likely that it just renumbered the grid upon input to the model. 

My _map file does contain topology; however, Im not sure how I would aggregate it to be usable by an UnstructuredGrid constructor. Would I need to create a new *.nc file and omit unnecessary vars or can stompy just pick out what it wants by the var names? 

Thanks so much! Your sfb_dfm code base has been especially helpful for my work. Out of curiosity, are you aware of any datasets reporting significant wave height in South Bay? Im trying to validate a SWAN model for South Bay.

Jacob

**Comment by jacobjcastaneda** [comment]
Clarifying that yes in fact DFMGrid() allows me to pass the _map and get my grid with perfectly matching indices for the cells to what they should be. The issue must be the renumbering issue with DFM, a setting I clearly did not disable. 

Thanks a ton!

Jacob
